apiVersion: apps/v1
kind: Deployment
metadata:
  name: plutus-sync
  labels:
    app: plutus-sync
spec:
  selector:
    matchLabels:
      app: plutus-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plutus-sync
    spec:
      containers:
      - image: odiosdado/oddevs:plutus-sync-1
        name: plutus-sync